import Nav from "@/components/Nav";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Link from "next/link";
import Sidebar from "@/components/Sidebar";
import BottomNav from "@/components/BottomNav";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={sans.className}>
            <body>
                <div className="flex justify-between">
                    <div className="flex flex-col justify-between w-1/4 h-screen p-3">
                        <div>
                            <h1 className="text-2xl font-bold">
                                <Link href="/">REDET</Link>
                            </h1>
                            <Nav />
                        </div>
                        <BottomNav />
                    </div>
                    <div className="w-full">{children}</div>
                    <Sidebar />
                </div>
            </body>
        </html>
    );
}
